"""Publish the gravity-aligned world frame recorded in world_frame.json.

This creates one TF tree:

    world
    ├── camera_color_optical_frame
    ├── left_fr3_link0
    └── right_fr3_link0

Do not start left_hand_pose.launch.py or right_hand_pose.launch.py alongside
this launch file: both publish a base -> camera transform, which would give
camera_color_optical_frame a second parent.
"""

import json
from pathlib import Path

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


DEFAULT_JSON_PATH = Path(__file__).with_name("world_frame.json")


def static_transform(parent, child, transform):
    """Create a static TF publisher from a JSON translation and quaternion."""
    x, y, z = transform["translation_xyz_m"]
    qx, qy, qz, qw = transform["quaternion_xyzw"]
    return Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        name=f"{parent}_to_{child}_static_tf",
        output="screen",
        arguments=[
            "--frame-id", parent,
            "--child-frame-id", child,
            "--x", str(x),
            "--y", str(y),
            "--z", str(z),
            "--qx", str(qx),
            "--qy", str(qy),
            "--qz", str(qz),
            "--qw", str(qw),
        ],
    )


def launch_setup(context, *args, **kwargs):
    json_path = Path(LaunchConfiguration("world_frame_file").perform(context))
    world_frame = LaunchConfiguration("world_frame").perform(context)
    camera_frame = LaunchConfiguration("camera_frame").perform(context)
    left_base_frame = LaunchConfiguration("left_base_frame").perform(context)
    right_base_frame = LaunchConfiguration("right_base_frame").perform(context)

    try:
        data = json.loads(json_path.read_text(encoding="utf-8"))
        transforms = data["transforms"]
        recorded_camera_frame = data["frames"]["camera_frame"]
        camera_transform = transforms[f"world_to_{recorded_camera_frame}"]
        left_transform = transforms["world_to_left_base"]
        right_transform = transforms["world_to_right_base"]
    except (KeyError, OSError, json.JSONDecodeError) as error:
        raise RuntimeError(f"Cannot load valid world-frame data from {json_path}: {error}")

    return [
        static_transform(world_frame, camera_frame, camera_transform),
        static_transform(world_frame, left_base_frame, left_transform),
        static_transform(world_frame, right_base_frame, right_transform),
    ]


def generate_launch_description():
    return LaunchDescription(
        [
            DeclareLaunchArgument(
                "world_frame_file",
                default_value=str(DEFAULT_JSON_PATH),
                description="Path to output generated by estimate_world_frame.py.",
            ),
            DeclareLaunchArgument(
                "world_frame",
                default_value="world",
                description="Name of the common parent frame.",
            ),
            DeclareLaunchArgument(
                "camera_frame",
                default_value="camera_color_optical_frame",
                description=(
                    "Camera child frame. It must not already have another TF parent."
                ),
            ),
            DeclareLaunchArgument(
                "left_base_frame",
                default_value="left_fr3_link0",
                description="TF frame name of the left robot base.",
            ),
            DeclareLaunchArgument(
                "right_base_frame",
                default_value="right_fr3_link0",
                description="TF frame name of the right robot base.",
            ),
            OpaqueFunction(function=launch_setup),
        ]
    )
